language: node_js
node_js:
- node
- '8'
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: ghBgYfrElI7AREbVcW99UlrpnykS945lOAqPgAYwNHJxxvsg62X8oXPR7TY+dBMrde1eJgnajP2d04cD/FM389FELTuEj2LvLR+HMkly/4o98j5utxLfj9L+hs2BZLuEYQkh9I6fjVJ9aDXiwbRdljV4Yp+od619pmK9FRFlFstGi3o46MpLpH7a4ANAJs9DND4XM5GzyOfoouWvjkaR6pdRzWnEbjJ63FV30YXW4AxxSFoKFYMmLrn6SP98alFqj3VjRzUiTcJUa3Wv+0+Zk0FM7NI0jTKLjGdYP7bPN6QDdgdvaQhqsBdbdOqpKu2DqYBvTAFqQnUa53ZaOg33aUdj/uoz1R1gZ4qjOXmaLS0X2zbe8WqCWFaZOX2x//muIZYouN5FMtJF/6AjTkQVfpKST8CXXcrh0O9GaEbyj46V3eLkxOi1AHybR1sFD2wduoaNeZ2ASa3khNkDYAKGL04sLTRMaEzckHN/se0h+/Gd/yqunfHrW2aVZ8T92s879JR0T3mWpX6sWytPgTUj9MqgDcfEI4xvk/Hhj6fc9qB8OOyPKov2fa1ASQO47TlXfGx8UvTocyVs2ul/EwUBvtfMFepwhO8Yi74kGMTgbouZ7WoCGt9MMeMC3cVT48aI5CwPys/9zfdX93jPs15yoNdL0rCRmTH1A4MCTKDN9Mk=
