language: node_js
node_js:
- node
- '8'
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: fgPBUMeUVRWk7cDpQ8inQiUHhRUgxwbfPU0ncDEb3wDBXA8Rqxi4pj4AT7Licog9DsAUnAFIlSOc22eOD/WCwENuCiVL0TUXd6CRXiqVBCqnJ3K4/4SMnhp+WlcE8CmDog0/5RaYzIuyB05dBsAOUn4SlqhxBh9DPcA0RV5xUvFmhXFNlu3Ng+AMLzMFZCWLkX4qq7WFn43osrwkCrxTlqWNDdxSy6++RUY1lH9yYxqAQujHe786kDExenVdZbgQdZv+tsgjCEvgXyu2omETUBuhzoXpAOG0LdgydsUAGKQzgjFmuqFp89yc8xuutCxsDN5WC4+PX3XB+S+ylutZwgVR7uj4y6Vk2s30Lsj4/hW3P3qV6QiOVgVB8jstjab5G4NH+sKff3KxayWOBzXdUM4cpxnjUrLT7q9MxZUgJsfCZjJWPAs4lhMbyRyh8hxPQD+Tu983s1VrHRQNe0dGMG3xVHholBOpqjYDgkEyhklEPM2mqzXF8OnJo8W+8TAiT+2mACc8q6rt9ICTrODNckkx8UB6lFHVHbVD7qoQCPD33bDWYNTprToaUjEuQVXus9xS/mcdPjB84RsDX7U/HcNRnP0TyeKaYygG6vQcer+Oq79TvZVVOwRM8I7ut/f0sIHWH2aSs9MYFk2FKk7AeKz/3SJjt5+di/+SvlUDUls=
