language: node_js
node_js:
- node
- '8'
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: "lI90J2lNZNV+rHA5UVpafq/kTJdx9mqUgpqMTDGXKBcuKda9P2rNJOXcgAiLIblh/EaSAiikvPrp1+QQjd1bAqfVrXVIzkK1UcexwqwLDV5j1r3F8CRCwenCM4bo7L0BIgz0gu56YzuQV8yrWNulMJJSgAOewG4ogKuAqh8Lg1CNa1ZuZwUHJdVoLT87jDO0VwWpTsCFvEtYdNA1F0x2VAVa4e80oerUwLtgW6bmCEx0Xwnsyy9kdIz3dJ8l5MCkEw6tZZoHSyQi4bX9+/KINOGGTU7l5ydgdWD9W6XfH4IYyMoQD2orxWZWB/Ou33qeaxmeiv7QVaos+fyEm+9mF6Gf+y6+OMQGSyXhyQi27mSKc/moRJE2BS9ogdyHLfu4DgITf4YpJTMOCK9dswDqdTOkzyOqLDF/BEcagcWKNzw3W9aFiMlyHx0NcmnA/RWYs+WJJ+O0Jx/V0vXjLokBMomi6zqe/6mhntBd04+csjEtgNPmR442OAfFBQI7Ungm7TpAAVrQ+JAuKO6o6ZqV4pqQnyXGnybvKNogx3hAR1+svh070rlCKt5Gw8VWjUhm2P7rlR+FqQ7lPIlwvgFA4mM5+2iZ03g3s7QudLTrvgAyzL4jjNwBGDf5o+XB68aulzTFYIUJ4a9X0COszTuzn9ZFF6d5zVSNALEA+TRF5vI="