language: node_js
node_js:
- node
- '8'
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: "sShEYlYGwgaUdU6Y/0eqafswvC1S5rAhd8Ytxr8Ir90ZMJaeD9aE3F8paatc5dZi4CBfVtbEb+t+ecXGguHJHbU0uGuO4Yr3mUGQtuQx+AzOQF0fAOyiSG77Fu/ZCq5cJUDx91nx1Y7szGiSDrMX2A27e4L0Xl40s9kxtjHrom32U8gDZgFnqtGg9aeMomVkzB9sKWPbA8v7zIgFMpjyjBnRxL0/y6KMiK4ja2dpIeX6hunDjbbSdiEfFAhrp146Z2CWwql1Lf3Z8kmHm3+FLMu0mhYXe7kLW9JJ3gIpIfEnZRBzPEGILeRaAeFVQgoWrdPQ1sP6XSvUvbpq+3iJttp7Hal6+uMGA6fG7BLNG9dzF2ombKWtRUKW2p9SC6JICaAIChat1H0PKekxldaZesy1FMz+q542jxkJ+fldGHNrDi0ETH6f9V/jF5uESll0O0p/9oQjJguZYwar7ZaZK3lsISKTWwcja0ptxPjOvkBMR40z9kBKmcCUKX+T4qvPXis3LUtP2Gng+iee8kzVp1tKkpaMC0wET6riQSOv/A7HZVQFS7pkNpUgT9ApkCWOatGvtShgf5bhR97Fz/dYgT4ppgLk5OacgBKc/khM+hbLazb2F5lorwMZcxjleoBQbAKKujEurfJWonMMEFS4NXq8gd7itOXlAvojeaFLBIs="
