language: node_js
node_js:
- "10.8.0"
addons:
  sonarcloud:
    organization: devchat
    token:
      secure: $SONAR_TOKEN
install:
- npm install
script:
  - sonar-scanner
  - npm run start
  - npm run heroku-postbuild
  - npm run test
cache:
  directories:
  - node_modules
  - client/node_modules
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_TOKEN
  app: dev-chat-01
  on:
    repo: addziedz/devChat
