language: node_js
node_js:
- node
- '8'
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: 8977c78d-43f0-43b7-9346-485732f0fe8e
  app: devChat
  on:
    repo: addziedz/devChat
