language: node_js
node_js:
- node
- '8'
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: BFgtGGEzUtPXu8IB2bQaOmpNIe2VVNTi9xoKHE3mBTqNGuoMWdlH13PPRpDK/Prkx87hdJqV++0YPX5yPE2dsrFp/PrYF6HwQ8Ix89qVSUJZaGKMCJNVmQhaOvqJ3dWRGzr8VeZndDLJKnFJ9gkXyef9WL4th30M5ijj2/wlhME3wDSMLQHHoQw15TJzwSAys2W7eGPDphSkTMi8CTikxhlvZikaYdN0eaiLFAlIdgglmPra63BnT1gMVFDpfOi2lCUCE6jsgN3e+ojkkZPnsaB/1Jz4Z7c7aZTVZpM162cFH7wzYnLVXwHPneu9izetFROS+XXI2Nq8DX2PyqnofArO0cLrUVN/LqOb0Z8d+eUKC1VehT2tE53fejMS+KciFT5DbTQQX2KXraLnEaFG8K3LjsUeIHj+gZylr6jhgEjiTq/eHP4HZxRKwIu/M2xJ80ohn+9cRF5aBwr3xGsywqhBzrEtYGfX3XNNryWunz5vIR/LCxbmmxEYbq6Q8tzpIkV9sU1fZQzYBNAS+J543UWM23lrVsUHyhl4Z5sIlHBFAPny+cfBU7d9MIFwb8zhJHqbc1AE0Eq1M3LdovpOs47JrpsIHkno5HlKKGYjhMMn7TnwjllNiI/p1ZT+45YuXXxzZg97WuW/EBYiZGvgODokIJaA2sny6KYmEIv1qMI=
