language: node_js
node_js:
- node
- '8'
cache:
  directories:
  - node_modules
deploy:
  api_key:
    secure: osO3d5gnnETIPsfvdbUPI277XO9lIhjAAsfIQDiKAiSnA8m8motrvq3MlIcn7ukUwRd78V9zc2pZOLmr2JP6iocifdISGaDXWgQKUKMvKxiJEtUHwD4RpBVYqvNIb5SxoTfOl6jZytc/cuAmvTwtfa5O3RbGumwbfqBB8RqUWWUrx7dsAgr8GSmuH4GAJ/iWPtw36aah5Gfs4zvPeNHSqGu4h2/K2Ra5oK4RaWygUdzlNhI+pQpa8Hcrs8RTKM1ot0a0F9bd5Sj4GRARBAcUV6C6qS5abVi3XTEZiogEMDk4rG8Mxh7AIStG5aaPaksH88+RfyivkLqeh/f4nWZkjAE4b/pKTWKcCQ6tgfn4hXQoDtoSmPUP263isNdKOHI23oaMzvKz7pNMVYUo5Bf62Ey3UkbvlvE0dOpYZMwBp7hblQkatPJdsf8x4zGNw/kny5Uf4t2m74YTlpH/2qwptUblrCtof8q5HFrbhePFIcTM8eBVX7QzQy3tPVr1rxOFOwaQ8dR7o43XyxGJpRbscw6/qByAp6QPqjNelbW0uc2CrlKFqxAVFZUzbGeitvjrkR9b7MStEmkR2vh+sY49NI9A7zALsDN4UTpZqP38WytcJnazvHcMstTSP23uVrc3gSI9pdJAb+uYg5QEz8wAXc6d7OeQL1JmaWDpwr84cEo=
