language: node_js
node_js:
- node
- '8'
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: g2Yqa164ihhJ31cEgeQtTPCFv/JfGT5/n8dpEeVVSEDW+8G7lF+AiQiE+OjkwwX7Sluwqmk5k8KMChsehGm6hdeVk5AZd8s29WjfUr1jkxXtnJlTjhiN3ZQv+xi28nDLKgwvZ4l2hQCe0amofCfZauU1U4VatkLibtdLMC0P2JzTSAbiF47e5nKgpIdav7z3xNECQWH+cy6mdFnIyD2fVwEx9t9lOlO0YBgx5WyMVOYXWmkMyKLAh6mLZLavon59Us2UYLiav1u0IzfqtpiXMHSrergGziSsEFKk8hg4elQbx/GgR4GdO4ikZN6tXZM51XlHATEBaQcFcnWkRnjycbwnoCmQS1lj4lFfLbK5g5bFmTxXLcVaQI7d3mGTsFyrRWUI3F3R9BwbiZRpl6heElj835WkPx6BzYXFIFKhH23nbUqrMJXsXnnoU3CnHCTYfjqjvvtKXg85dAXztocuvUkN1E4fL6bS/iMbEaVH+5fB3yYChrveJpwqfM/8X85wAZIXzRHkF1pG78VeOUsSU0u837wvMOe/Bs/D2cRd944jOj1Vd6fab7CCLJpWfroakGw/Ml1S9d84jMV0Gb0lGfKcH9Ruz3WcXh5AUyMAOLFVSvmYhSvgtgGvAD0TKfdKg7MQHMzBIf1PGDmCdqwhCE1hKyjcDcI8p0ydA0reog8=
  global:
    secure: CimY/smT8becUJGU0kSHmGvQePRy5/S4KYrQhtpK6Zq/6mGg1OvfNyZ0ork2FVgKyoulxAQ+2qyltDtf6f+JN7iSt8rdIJpO887FSdDjMuVL2SsaFTZkCGdQwRNeE0sXSP0Fr/Y4fsb7JxPncHFkO4Z0iYDDo7fKoeFwsljskovSCAtNHRbGCC4t/aET1b0hhprFJCvsQxlkQi693Fo8aRcvkWh7H4gdxQCI1GN41Oj0BErA73Mh/e+0sg0nhElFVpzJNASThNsO9wmlA6/2NFt2312LZls+97HsYqDeTiEr7iemC3ZbFFh/YG2rrJS+C1SXaXWY/AhgyeG2dxGxyigOUT0ODn6jrziktg9+QCRVah94ohZxKy9OTjwn0bYPrUecFFiIHenDuu3J7/XAfoXPYRS92OOCuN3bjSj3R09sIeU7bovfHcM0u4JasnH9W2fgzjrQxUCy42s5xxhyT5tvkjh18W/3/08c/I4duDHm9hlN02aCmTuoMjSlkoOXIIWSds+KAMNRDArye46JaomrSUUMenS41RB9MiER+OCG8n3CNo7RyiEdK3TlZ/4W2da7Zsi32conwHMPtwWr8m52YHV85TAP++tGZnmIZdLFPgm/FAnFcpcGD5OL7Msis9zTcHKW4E/9IIi1/rSek07ZZFf4F0NCK1PPmxF/82s=
