language: node_js
node_js:
- node
- '8'
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: g2Yqa164ihhJ31cEgeQtTPCFv/JfGT5/n8dpEeVVSEDW+8G7lF+AiQiE+OjkwwX7Sluwqmk5k8KMChsehGm6hdeVk5AZd8s29WjfUr1jkxXtnJlTjhiN3ZQv+xi28nDLKgwvZ4l2hQCe0amofCfZauU1U4VatkLibtdLMC0P2JzTSAbiF47e5nKgpIdav7z3xNECQWH+cy6mdFnIyD2fVwEx9t9lOlO0YBgx5WyMVOYXWmkMyKLAh6mLZLavon59Us2UYLiav1u0IzfqtpiXMHSrergGziSsEFKk8hg4elQbx/GgR4GdO4ikZN6tXZM51XlHATEBaQcFcnWkRnjycbwnoCmQS1lj4lFfLbK5g5bFmTxXLcVaQI7d3mGTsFyrRWUI3F3R9BwbiZRpl6heElj835WkPx6BzYXFIFKhH23nbUqrMJXsXnnoU3CnHCTYfjqjvvtKXg85dAXztocuvUkN1E4fL6bS/iMbEaVH+5fB3yYChrveJpwqfM/8X85wAZIXzRHkF1pG78VeOUsSU0u837wvMOe/Bs/D2cRd944jOj1Vd6fab7CCLJpWfroakGw/Ml1S9d84jMV0Gb0lGfKcH9Ruz3WcXh5AUyMAOLFVSvmYhSvgtgGvAD0TKfdKg7MQHMzBIf1PGDmCdqwhCE1hKyjcDcI8p0ydA0reog8=
  app: dev-chat-01
  on:
    repo: addziedz/devChat
