language: node_js
node_js:
- node
- '8'
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: Bu3zgv4CPgc3ZYAgQTB7epernqVh8HoRXIGBvN54A0eePu4k7ruL92KA2tDbO7bD5pSzQrZhGVE32xwmj/b7W5uzRvPxanoMv89cmKeuAshBGLtrgH982kw92mmrHDtrwEMDa4wFpvajP0Sl+z/jIoe6WGhJbw4TfD3LfHjzNcFxiHL+CNvTcqI6jpOn84giC+dOluRLElwz1FNYDHgju0AaZSJ5+AfydRiWjZKruCnHxXt8JpaiipzfSZwJC8ziXlvdBL0uRMViJ+9pv2sfrMyIU1D9glNWs8Pk4NZfqAXVXxrk04b81sZ5uS4lc2XkX0QWDf7rsnEoaVp38yhT/1oTtGOe/u+DCGrnXBb1xd0s6hzPrLKl2hJQk3kCZSZZCk2Fm0n+3kBv9l9LcGCtr7RLUWeMY07/WDbgChxrXP9MnvRABS8TMGTxflymIFjVJR83Z/ebPOnQrbpsSKOCnJAH6Gg5rEejYwuioI2POGn5XXuVepk7YKCkaf3isi+kfAz+kYaGFj3dKgwAGzrsiPLwlKDR97JOy1zl9BukGnjA/1oIujCjGZ74TlvYGk10x1ok1sTkxcjb17XDhhQQr5BrXEO8BZRj8Cc39eF3VnHoqoUiOj8b4h7eaa5m1io5h5ZbwjS3OsysYrSuHbxU7KqfkcSEgJ8ore2zb4svtbc=
  app: devChat
  on:
    repo: addziedz/devChat