language: node_js
node_js:
- node
- '8'
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: "joTLMx2cXELFbjx+YmLXH7NRFh5mbiMmNjD+xpjBYj9Nf88Gzfa2j5pz6KE2lhKeas16egbcVwCB2K16mdt0HAOsNyVY0xChfZD75xZsfyp7ZfwWPzqsE93E+RJ0usp05/W6seCGqJAj33dG5jBQdnz+mwnSF+oIm4SkyAUzTALNoHqS+P7aZyjb4JL0nj8dWtCmO0jWpx1XRepOkLuMjfgsqIcBpDpa3uqsZ4PQzkanFJghyw6bBH8+BXr2QYnCaG8BHtT+UIAzsbtKbRJWW/S1Vt+NQFA1+IosCGKY/wLWLYhdgNm49YZ90ad9pQCoIB5fhmygFwuvWdiQ1MJt58pDna8ndpRdAQDNYN+mTLQOB+28gvQWa2aLUS0sXgKv33Tl1+aYDwgnTN9TQvThGKA2rUihNURue3MeVyuHAUYa+s8wIWy32yQ1O1ofRlZVEh5n8UFDKtXV7Zjhbt0YbMZKfrSVC/vZM+dzg75++gf6wQWypK1djXd9YKm3QEk2Mt+jWHMGL7NeNiaySf+IkWRvv/JFNTGAuqPzn7aFzBKYxurZ1r/eu6Ytb8quaOKsz/mykZFNvgMnjdIiJKjL/6+V9CJPg+5Vp4OHtEBG823GGIxRD+bdqEyyLZxCi5cui+LdZUSlvH6f8uhZucskknOlOuMrhIVTgf62673l++g="
